server:
  port: 8011
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangle777/spring-cloud-config.git
          search-paths: zhangle777/spring-cloud-config
  application:
    name: config-service
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-port: 8001
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
