server:
  port: 8011
spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true    #启动快速识别错误的配资源
          uri: https://github.com/zhangle777/spring-cloud-config.git
          search-paths: zhangle777/spring-cloud-config #扫描仓库下文件路径
      discovery:
        enabled: true
    bus:
      trace:
        enabled: true
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh