server:
  port: 8022
spring:
  application:
    name: service-ribbon
eureka:
  instance:
    hostname: localhost
  client:
    eureka-server-port: 8001
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    fetch-registry: true
    register-with-eureka: true