server:
  port: 8040
spring:
  application:
    name: service-zuul
eureka:
  instance:
    hostname: localhost
  client:
    eureka-server-port: 8001
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    fetch-registry: true
    register-with-eureka: true
zuul:
  routes:
    feign:
      path: /feign/**
      serviceId: eureka-feign
    client:
      path: /client/**
      serviceId: eureka-client