server:
  port: 8010
spring:
  application:
    name: eureka-client
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/
    fetch-registry: true
    register-with-eureka: true